spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/austin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # springboot 默认连接池 hikari 配置
    hikari:
      # 最小连接数
      minimum-idle: 5
      connection-test-query: select 1 from dual
      # 最大连接池梳理，默认10
      maximum-pool-size: 20
      # 开启自动提交
      auto-commit: true
      # 最长多久空闲释放连接，默认10分钟，
      idle-timeout: 30000
      pool-name: HikariCP
      # 连接最长存活时间毫秒，默认30分钟
      max-lifetime: 60000
      # 等待超时时间，默认30秒
      connection-timeout: 30000

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: spring-boot-demo
      # 手动提交
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 60000
    listener:
      log-container-config: false
      concurrency: 5
      # 手动提交
      ack-mode: manual_immediate



mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  # 设置扫描的 mapper.xml
  mapper-locations:
    - classpath:mapper/*.xml

pagehelper:
  auto-dialect: true
  helper-dialect: mysql
  reasonable: true
  params: count=countSql


management:
  endpoints:
    web:
      exposure:
        include: '*'

## 简单日志配置
logging:
  ##  默认情况下 SpringBoot 将日志输出到控制台，不会写到日志文件。
  ##  需要设置日志文件输出路径
  ##  logging.file 或 logging.path 属性。二者不能同时使用，如若同时使用，则只有 logging.file 生效。
  # logging.file.name=文件名（设置文件，可以是绝对路径，也可以是相对路径。例：logging.file=my.log）
  # logging.file.path=日志文件路径（设置目录，会在该目录下创建spring.log文件，并写入日志内容。例：logging.path=/var/log）
  file:
    name: austin.log
    #path: ~/idea-project/spring-boot-action/logs/action-logback/
  level:
    com.kubertX.auxtinX: info
    # logging.config 设置使用详细的 logback.xml 配置
    # 不设置会搜索 logback-spring.xml 和 defaults.xml
    root: info
  config: